services:
  app:
    build: .
    container_name: next
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /.next
      - /node_modules
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asal123
      MYSQL_DATABASE: mdbrafleh
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
